### ISSUE TITLE
Should the destination bucket already exist?

### ISSUE THREAD

**Issue by danielcrisp** [adieuadieu/serverless-sharp-image#31]
If I run `yarn test` when the destination bucket does **not** exist then the tests fail with:

    [NoSuchBucket: The specified bucket does not exist]

However, when the bucket **does** exist then the tests pass but `yarn deploy` fails with this error:

    An error occurred while provisioning your stack: imageDestinationBucket
     - XXXXXXXXXXXX already exists.

This seems somewhat contradictory!

**Comment by danielcrisp** [comment]
Just seen the comment in the troubleshooting section about this... let me try

**Comment by danielcrisp** [comment]
Ok, now I'm getting this error:

    An error occurred while provisioning your stack: S3BucketXXXXXXXX
     - XXXXXXXX already exists.

Slightly different. It is referring to the source bucket this time.

**Comment by adieuadieu** [comment]
Hi @danielcrisp. I'm sorry to hear you're having difficulties using `serverless-sharp-image`.

The issue you're running into is a bit of a catch-22. In order to run the unit tests, there needs to be an s3 bucket. But, to deploy, Serverless also tries to create those buckets. If you make the buckets to run the unit tests, then Serverless will complain that they already exist. Ugh.

The easiest solution is to manually create your S3 bucket(s) yourself, and remove the `imageDestinationBucket` section from the `resources` section in `~/serverless.yml` ([line 81](https://github.com/adieuadieu/serverless-sharp-image/blob/master/serverless.yml#L81)).

Another solution is to deploy before running the tests (I realise this is ass-backwards, but it'll get you going in a dev environment.) By deploying first, the correct AWS Cloud Formation template can be generated and deployed—which includes creating the bucket. This means you won't get that provisioning error. Then, the unit tests will be able to make use of the same bucket without you having to manually create it. To deploy directly, you can run `./node_modules/.bin/serverless deploy` within the project's root directory. Or, if you have `serverless` installed globally, `serverless deploy` within the project root should also work.

When I deploy this function in production, I end up setting up the s3 buckets manually because I don't want them to get accidentally deleted—furthermore, the source buckets are usually already in use and contain images before I add this function, and so it's impossible to create the bucket from scratch—since it's already in production use. In this case I remove the `resources` section from serverless.yml so that Serverless and CloudFormation don't try to create the bucket resource.

**Comment by danielcrisp** [comment]
Great - thanks for the indepth explanation

**Comment by superandrew213** [comment]
@adieuadieu I'm doing this:

> The easiest solution is to manually create your S3 bucket(s) yourself, and remove the imageDestinationBucket section from the resources section in ~/serverless.yml (line 81).

But I still get the error that the source bucket still exists. If I remove the event from the lambda function  too (like you say in the troubleshooting section), it deploys fine. But how will the resized function trigger without the event?

I'm trying to disable the creation of the S3 buckets (they will already exist).

**Comment by superandrew213** [comment]
This seems to be an issue with Cloudformation https://github.com/serverless/serverless/issues/3968. specifying the s3 event will create the bucket

**Comment by adieuadieu** [comment]
@superandrew213 yea; it's quite annoying. The simples work-around I'm aware of that I've also tried myself is to remove the s3 event from the `serverless.yml` configuration and set it up manually in the AWS web Console. An alternative might be to use [this plugin](https://github.com/matt-filion/serverless-external-s3-event) but I haven't tried this.
